---
# use -u flag instead of specifying user and --ask-pass if no SSH key pushed to remote machine
# use --ask-become-pass flag

- name: Install Vim
  hosts: all

  tasks:
  - name: Install required packages
    package: 
      name: "{{ item }}"
    with_items:
      - git
      - gcc
      - make
    become: yes

    # Takes most recent version from master - not very secure TODO: specify version?
  - name: Clone Vim repository
    git:
      repo: "https://github.com/vim/vim.git"
      dest: "{{ ansible_user_dir }}/vim"

  - name: Build Vim
    make:
      chdir: "{{ ansible_user_dir }}/vim"
  
  - name: Install Vim
    make:
      chdir: "{{ ansible_user_dir }}/vim"
      target: install
    become: yes

  - name: Remove Vim repository
    file:
      path: "{{ ansible_user_dir }}/vim"
      state: absent

  - name: Copy .vimrc
    copy:
      src: dotfiles/.vimrc
      dest: "{{ ansible_user_dir }}/.vimrc"

  - name: Install Vundle
    git:
      repo: "https://github.com/VundleVim/Vundle.vim"
      dest: "{{ ansible_user_dir }}/.vim/bundle/Vundle.vim"

  - name: Install Vim plugins
    command: vim +PluginInstall +qall

