---
# use -u flag instead of specifying user and --ask-pass if no SSH key pushed to remote machine
# use --ask-become-pass flag

- name: Remote configuration
  hosts: all

  tasks:
  - name: Install required packages
    package: 
      name: "{{ item }}"
    with_items:
      - tar
      - gcc
      - make
    become: yes

  - name: Create {{ ansible_user_dir }}/tmux directory
    file: 
      path: "{{ ansible_user_dir }}/tmux"
      state: directory

    # TODO: Specify versions
  - name: Get tmux and its dependencies' tarballs
    get_url: 
      url: "{{ item }}"
      dest: "{{ ansible_user_dir }}/tmux/"
    with_items:
      - "https://github.com/libevent/libevent/releases/download/release-2.1.8-stable/libevent-2.1.8-stable.tar.gz"
      - "ftp://ftp.invisible-island.net/ncurses/ncurses-6.1.tar.gz"
      - "https://github.com/tmux/tmux/releases/download/2.8/tmux-2.8.tar.gz"
   
  - name: Unarchive sources
    unarchive: 
      src: "{{ ansible_user_dir }}/tmux/{{ item }}"
      dest: "{{ ansible_user_dir }}/tmux/"
      remote_src: yes
    with_items:
      - libevent-2.1.8-stable.tar.gz
      - ncurses-6.1.tar.gz
      - tmux-2.8.tar.gz

  - name: Configure the tmux dependencies
    command: ./configure
    args:
      chdir: "{{ ansible_user_dir }}/tmux/{{ item }}"
    with_items:
      - libevent-2.1.8-stable
      - ncurses-6.1

  - name: Build the tmux dependencies
    make: 
      chdir: "{{ ansible_user_dir }}/tmux/{{ item }}"
    with_items:
      - libevent-2.1.8-stable
      - ncurses-6.1

  - name: Install the tmux dependencies
    make: 
      chdir: "{{ ansible_user_dir }}/tmux/{{ item }}"
      target: install
    with_items:
      - libevent-2.1.8-stable
      - ncurses-6.1
    become: yes

  - name: Configure tmux
    command: ./configure
    args:
      chdir: "{{ ansible_user_dir }}/tmux/tmux-2.8"

  - name: Build tmux
    make: 
      chdir: "{{ ansible_user_dir }}/tmux/tmux-2.8"

  - name: Install tmux
    make:
      chdir: "{{ ansible_user_dir }}/tmux/tmux-2.8"
      target: install
    become: yes

  - name: Remove tmux and its dependencies' sources
    file: 
      path: "{{ ansible_user_dir }}/tmux"
      state: absent

  # Considered not secure according to https://unix.stackexchange.com/a/357867
  - name: Add /usr/local/lib to search path (RHEL only)
    blockinfile:
      path: "/etc/ld.so.conf"
      block: |
        # Fix for tmux not being searched for in /usr/local/lib on RHEL systems
        /usr/local/lib
    become: yes
    when: ansible_facts['os_family'] == "RedHat"

  - name: Update /etc/ld.so.cache file (RHEL only)
    command: ldconfig
    become: yes
    when: ansible_facts['os_family'] == "RedHat"

  - name: Copy .tmux.conf file to remote server
    copy:
      src: dotfiles/.tmux.conf
      dest: "{{ ansible_user_dir }}/.tmux.conf"

